sudo: required
services:
- docker
addons:
  apt:
    packages:
    - golang-go
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
- go get github.com/pauldotknopf/github-release-sync
- docker pull dpendolino/darch-arch-base
script:
- "./build && ./deploy"
env:
  matrix:
  - PATH="$PATH:$HOME/go/bin"
  global:
    secure: VTVtMi0F0HkKQUlSuAdvEFGHkukT8sNlGCiEFZ2dHye6OAj56aKENUEyYIS+6jyzJNy48eXuVX/FQLx+8HWYzHqHWObR1ApNkHm5lRcb6fOmDEPke2ux/QaT2iRxUR43e9JQ1tTXeSEJbXT1bFPnR9Rc12phPvm0gyhWlK9YgZb3p5+5CTnGN2SMSO0LAn9LbOexBByyzt8KHaRCn6D2+ngAx+okxxrarhH6hbfdfzlT/9gyCJHWGaRPfjML6t8KnXkklIkgqxxuaZU1SgBexh2pGeKPRBexKfSPz6WUYGu2DuWgjhjFZvrvj1Q26Qa8mYxnraympOwZqJ32eyam5eMsROkOxVu5HQpeah3Y1V3UF0QhsLDqc36e4dPsz5hHGna8a4bJHgZIAWIymbQbdjKcYbfOH5Wtd7RkZ39LsfA9UX4HpFt1BFHB6XO3uGWQwxiSRSddq7y5GWGwuW21H/rDq/9g70aK97hftSb8a3ov5dTS6s3Z0yVUjHIN+S2idTOK1UFjn6v5bYcjf7CcE5jU8zkLJ3zirZaFMakcnyM2ebIpWFmyjJKRe95D19ig34WV30/TIysu8RX7TuC/snKxojLqYn1ENrYQLhwWsud13syslnVk/CUSzpGCu8FviR+q1eZbxwfBfh2/DDY/gOGZOmu6xpiPHargVDzflhQ=
notifications:
  slack:
    secure: SwYdz12C1EYKWMZE/8EfB4DfeygqRYzmMa82H5i5/k9jEWGUWYLS4ff/PfHUDpbbgWgcpoxha4l2zWMpptVoeRAx7rJChS+ByjHeWYNNRYt4I9QQwzc7pJ9KlTbHz7XtdSlf7heIQUdVP8pSZmdF0UTsNfRCB+LpYllcLcnCkaRcqo+zjp132tXSfxynv4cyKeszNP5YG498dQtRSlV8PM57BSa0uhazw1UTX1NK3AiYt2+eVqysOHx0Msiqz3Sc61jgRQ0gXzXbnVA128/6Fbfo6x33eFfDZhuIHwIEGQj0/ttnqpM7CX3sQyVbQfGgrEU3nkFYEfSMyKkVeyjbnrA9lYe8yciUqT294SRJR1uTaJfXaPuM8gONQAbUPkUTYA/o4qkGgJxuPqcbPRbK0/b0cUYYV89BscwUkQO/tJ+8O4o56+ewmbDyj8F5zfHLXfgiY8zHdtzWNOyDyFTZJwciDWGAmnJ6lr1m6keSVcXwcuOOh7831KeNoHLnOIvMTDvQGWiukUIQhfEfKv93GnjgYVBpsSP6586pivhnK1/WOj5uUOl2TsSA390WK5hXR9pNUZXgQYRUA/ruiedcOCtQuzGytIvB3hU1ekFfR+h2hL2GyEtblJk70ejbidnTruwNllIRb4OgSdlSJ85v3awCacsmB5oCeIUfPhKa5Pg=
