#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

github-release-sync --dir $DIR/packages --owner dpendolino \
--repo binary-repos --tag arch-linux-release --overwrite \
--prune --access-token "$GITHUB_ACCESS_TOKEN"
